POST http://localhost:3333/categories
Content-Type: application/json

{
  "name": "Bebidas",
  "icon": "🍹"
}

###
POST http://localhost:3333/categories
Content-Type: application/json

{
  "name": "Hamburgueres",
  "icon": "🍔"
}

###
POST http://localhost:3333/categories
Content-Type: application/json

{
  "name": "Promocoes",
  "icon": "🏷️"
}

###
POST http://localhost:3333/categories
Content-Type: application/json

{
  "name": "Pizza",
  "icon": "🍕"
}

###
GET http://localhost:3333/categories
Content-Type: application/json

###
GET http://localhost:3333/products
Content-Type: application/json

###
POST http://localhost:3333/products
Content-Type: application/json  

###
POST http://localhost:3333/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Pizza quatro queijos
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

deliciosa pizza quatro queijos com borda simples
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagePath"; filename="quatro-queijos.png"
Content-Type: image/png

< C:\Users\Erildo\Desktop\www\WAITERAPP/api/uploads/quatro-queijos.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

3000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

68ea5025a09416dd52f7ecda
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ingredients"

[
  { "name": "Mussarela", "icon": "🧀" },
  { "name": "Parmesão", "icon": "🧀" },
  { "name": "Gorgonzola", "icon": "🧀" },
  { "name": "Catupiry", "icon": "🧀" }
]
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:3333/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

coca-cola
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

lata geladinha
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagePath"; filename="coca-cola.png"
Content-Type: image/png

< C:\Users\Erildo\Desktop\www\coca-cola.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

700
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

68ea5025a09416dd52f7ecdb
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:3333/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

suco de laranja
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

delicioso suco de laranja natural
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagePath"; filename="suco-de-laranja.png"
Content-Type: image/png

< C:\Users\SeuUsuario\Desktop\www\suco-de-laranja.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

1500
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

68ea5025a09416dd52f7ecdb
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ingredients"

[
  { "name": "laranja", "icon": "🍊" },
  { "name": "manjericao", "icon": "🌿" }
]
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:3333/products
Content-Type: application/json

###
GET http://localhost:3333/categories/68ea5025a09416dd52f7ecdb/products
Content-Type: application/json 

###
POST http://localhost:3333/orders
Content-Type: application/json

{
  "table": "4",
  "products": [
    { "product": "uuid", "quantity": 2 },
    { "product": "uuid", "quantity": 1 }
  ]
}

###
GET http://localhost:3333/orders
Content-Type: application/json

###
PATCH http://localhost:3333/orders/uuid
Content-Type: application/json

{
  "status": "DONE"
}

###
DELETE http://localhost:3333/orders/uuid

