services:
  database:
    image: bitnami/postgresql
    container_name: db_waiterapp
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=iurd
      - POSTGRESQL_PASSWORD=iurd
      - POSTGRESQL_DATABASE=waiterapp
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
