version: "3.9"

services:
  database:
    image: mongo
    container_name: db_waiterapp
    restart: always
    ports:
      - 27017:27017
    environment:
      - POSTGRES_DB=waiterappdb
    volumes:
      - pgdata:/data/mongo
    # network_mode: host

  app:
    build: .
    container_name: waiterapp
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    # network_mode: host

volumes:
  pgdata:
    driver: local
